#cloud-config
disable_root: true
timezone: Europe/Moscow
repo_update: true
repo_upgrade: true
apt:
    preserve_sources_list: true

users:
    - default
    - name: ubuntu
      shell: /bin/bash
        
runcmd:
    - wget https://gist.githubusercontent.com/danoque/ea6526ef513cfc262ddc2c4efe4ba325/raw/51ab1109e3f9c94d743deb42231cf732589b1bc5/install_ruby.sh
    - wget https://gist.githubusercontent.com/danoque/005d02007c34b556790052f422c086d4/raw/15bcbdb5e72ef28851e260b5651a6df67bfff33e/install_mongodb.sh
    - wget https://gist.githubusercontent.com/danoque/1b844805594fe72a1ea3bd88e6c3c224/raw/16afbc2ea1556eafe0de26430ecaf4c22c59199a/deploy.sh
    - bash install_ruby.sh
    - bash install_mongodb.sh
    - bash deploy.sh
